"""create_banking_platform_tables

Revision ID: f109b16dbaf0
Revises: 
Create Date: 2026-09-25 22:49:00.696979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f109b16dbaf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.String(length=100), nullable=True),
    sa.Column('employees', sa.String(length=100), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('loan_exposure', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('eta', sa.String(length=50), nullable=True),
    sa.Column('last_analysis', sa.String(length=100), nullable=True),
    sa.Column('ceo', sa.String(length=255), nullable=True),
    sa.Column('hq', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('raw_financials', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_risk_level'), 'companies', ['risk_level'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('officer', sa.String(length=255), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_thread_id'), 'audit_logs', ['thread_id'], unique=False)
    op.create_table('credit_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('credit_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=50), nullable=False),
    sa.Column('credit_rating', sa.String(length=20), nullable=False),
    sa.Column('probability_of_default', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('positive_factors', sa.JSON(), nullable=True),
    sa.Column('ai_insights', sa.JSON(), nullable=True),
    sa.Column('workflow_status', sa.String(length=50), nullable=True),
    sa.Column('current_node', sa.String(length=50), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('is_llm_generated', sa.Boolean(), nullable=True),
    sa.Column('data_provenance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_evaluations_company_id'), 'credit_evaluations', ['company_id'], unique=False)
    op.create_index(op.f('ix_credit_evaluations_id'), 'credit_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_credit_evaluations_risk_category'), 'credit_evaluations', ['risk_category'], unique=False)
    op.create_index(op.f('ix_credit_evaluations_thread_id'), 'credit_evaluations', ['thread_id'], unique=False)
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('balance_sheet', sa.JSON(), nullable=True),
    sa.Column('income_statement', sa.JSON(), nullable=True),
    sa.Column('cash_flow', sa.JSON(), nullable=True),
    sa.Column('ratios', sa.JSON(), nullable=True),
    sa.Column('market_fx_data', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_data_company_id'), 'financial_data', ['company_id'], unique=True)
    op.create_index(op.f('ix_financial_data_id'), 'financial_data', ['id'], unique=False)
    op.create_table('human_review_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('officer', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('original_category', sa.String(length=50), nullable=False),
    sa.Column('adjusted_category', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['credit_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_decisions_company_id'), 'human_review_decisions', ['company_id'], unique=False)
    op.create_index(op.f('ix_human_review_decisions_evaluation_id'), 'human_review_decisions', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_human_review_decisions_id'), 'human_review_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_human_review_decisions_thread_id'), 'human_review_decisions', ['thread_id'], unique=False)
    op.create_table('loan_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('pricing_spread', sa.String(length=100), nullable=True),
    sa.Column('covenants', sa.JSON(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['credit_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_loan_recommendations_company_id'), 'loan_recommendations', ['company_id'], unique=False)
    op.create_index(op.f('ix_loan_recommendations_id'), 'loan_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_recommendations_id'), table_name='loan_recommendations')
    op.drop_index(op.f('ix_loan_recommendations_company_id'), table_name='loan_recommendations')
    op.drop_table('loan_recommendations')
    op.drop_index(op.f('ix_human_review_decisions_thread_id'), table_name='human_review_decisions')
    op.drop_index(op.f('ix_human_review_decisions_id'), table_name='human_review_decisions')
    op.drop_index(op.f('ix_human_review_decisions_evaluation_id'), table_name='human_review_decisions')
    op.drop_index(op.f('ix_human_review_decisions_company_id'), table_name='human_review_decisions')
    op.drop_table('human_review_decisions')
    op.drop_index(op.f('ix_financial_data_id'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_company_id'), table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index(op.f('ix_credit_evaluations_thread_id'), table_name='credit_evaluations')
    op.drop_index(op.f('ix_credit_evaluations_risk_category'), table_name='credit_evaluations')
    op.drop_index(op.f('ix_credit_evaluations_id'), table_name='credit_evaluations')
    op.drop_index(op.f('ix_credit_evaluations_company_id'), table_name='credit_evaluations')
    op.drop_table('credit_evaluations')
    op.drop_index(op.f('ix_audit_logs_thread_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_risk_level'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
